created server_express
AndriiDobronos/nodejs24_hw_AndriiDobronos pull request #10
Opened 2024-05-20 14:04 UTC by AndriiDobronos

2024-05-20 17:53 UTC, evhenious commented on main.js
> +require('dotenv').config();
А для чого ти повторно це робиш? У тебе ж зверху вже є все те саме

2024-05-20 17:54 UTC, evhenious commented on main.js
> +const {server_express} = require('./server_express');
Можна було не додавати це сюди :)

2024-05-20 17:59 UTC, evhenious commented on server.js
Я не сильно впевнений чому цей доволі великий кусок змін тут. То якісь правки попереднього коду вдогонку? Давай наступного разу, якщо багато чого поправляєш в старому матеріалі, який напряму не стосується поточного завдання, будем це виносити окремим пулріквестом? Бо складно фільтрувати коли воно все одним заходом йде

2024-05-20 18:00 UTC, evhenious commented on serverWithEndpoints.js
Якщо спочатку закомітити файл, а ПОТІМ додати його в гітігнор, нічого не вийде - як бачиш, файл все одно тут

2024-05-20 18:02 UTC, evhenious commented on server_express.js
> +const { logger: loggerConfig} = require('config');
```javascript
const { server: srvConfig, logger: loggerConfig } = require('config');
```
Не потрібно розвозити на декілька окремих імпортів, якщо ти просто дістаєш із одного місця декілька речей

2024-05-20 18:07 UTC, evhenious commented on server_express.js
> +    this.server_express;
Знову ні

У тебе строка 14 відповідає за запуск сервера. Строка 14 виконається НЕЗАЛЕЖНО від того, стандалоун скріпт це або через імпорт. Тому оці твої кондішени не роблять нічого корисного. Тоді вже ти мав зробити якось так
```javascript
if(require.main === module) {
  logger.info('executed as a standalone script');
  app.listen(........);
}

module.exports = {
  startServer: () => {
    console.log(`Server started from point: main.js`)
    app.listen(........);
  }
};

```


Доречі, а що має робити оця інструкція? `this.server_express;` ??

2024-05-20 18:09 UTC, evhenious commented on routers/users.js
> +});
Успішний ріспонс має формуватись тут. У тебе ж сюда навіть потік виконання ніколи не дойде

2024-05-20 18:14 UTC, evhenious commented on middlewares/validators.js
> +const usersDataValidator = async (req, resp, next) => {
У тебе зараз валідатор і основна логіка в одну кучу. Те що має тут бути - валідатор окремо, основний хендлер окремо.

І валідатор не впливає на успішні відповіді, він тільки фейлить з помилкою 400 якщо валідація не пройшла, і передає керування далі через next() якщо валідація пройшла

В роутері це все повинно виглядати так

```javascript
router.post('/user', validateUserData, (req, resp) => { 
  // main handler where you make successful response
  resp.status(201).send('user created');
});

router.get('/user/:userId', validateUserId, (req, resp) => { 
  // main handler where you make successful response
  resp.json({ userId: req.params.userId });
});

router.delete('/user/:userId', validateUserId, (req, resp) => { 
  // main handler where you make successful response
  resp.status(204).send();
});
```

2024-05-20 18:18 UTC, evhenious commented on middlewares/validators.js
> +        await userIdSchema.validate(req.url.slice(1,req.url.length));
Зверни увагу - валідатор не привязан до конкретного урла. Це мідлвер, який може бути накинутий будь-куди. Тому ніколи не спирайся в мідлверах на щось інше окрім req.params або req.query

2024-05-20 18:20 UTC, evhenious commented on middlewares/validators.js
> +        resp.status(req.method === 'DELETE' ? 204 : 200);
Валідатор повертає 400 і помилки якщо валідація даних фейлиться, і передає керування далі через next() якщо валідація пройшла. Успішні відповіді формуються далі в іншій логіці

2024-05-20 18:25 UTC, evhenious requested changes
Основне:
Розділи будь ласка валідатори від основної логіки.
Поправ звідки валідатор бере значення userid

* те що не стосується напряму завдання, я не сильно дивився

2024-05-21 08:26 UTC, AndriiDobronos commented
Дякую що так уважно і ретельно розібрали мою роботу !

2024-05-21 19:30 UTC, evhenious commented on server_express.js
> +if(require.main === module) {
Всю конструкцію строк 13-23 краще тримати в самому кінці. Буде нормальна послідовність, коли ти робиш сетап, а потім запускаєш сервер. Та й експорти краще тримати в кінці, за можливості

2024-05-21 19:31 UTC, evhenious approved these changes

2024-05-21 19:31 UTC, merged