Homework 2 1
AndriiDobronos/nodejs24_hw_AndriiDobronos pull request #3
Opened 2024-04-26 14:59 UTC by AndriiDobronos

2024-04-26 19:35 UTC, evhenious commented on secondary.js
Скопіпастив весь контент мого репозиторія? )))

2024-04-26 19:43 UTC, evhenious requested changes
Бачу дві проблеми:

1. при будь-яких значеннях LOG_LEVEL в .env файлі у тебе працює тільки logger.warn
2. COLORS_ENABLED=0 - а кольори не виключаються

Спробуй порішати

2024-04-29 11:27 UTC, evhenious commented on main.js
> +const {logLevel} = require("./config/default");
звертання до ключа logLevel із config чимось відрізняється від ключа colorsEnabled? :) для чого зроблена різниця?

2024-04-29 11:30 UTC, evhenious commented on utils/logger.js
> +function getLogger(moduleName,colorsEnabled,logLevel) {
взагалі, сама ідея передавати конфіг ззовні хороша. Просто тоді краще передавати логгер конфіг не двома окремими параметрами, а одним об'єктом. Я тобі закомітив трохи допомоги, показав як це зробити краще, подивись

2024-04-29 11:31 UTC, AndriiDobronos commented
Відмітив для себе що можна звертатись так і так якщо колись буду
переглядати це ж мій учбовий проєкт.


Пн, 29 апр. 2024 г. в 14:27, Yevhen Hraivoronskyi ***@***.***
>:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In main.js
> <https://github.com/AndriiDobronos/nodejs24_hw_AndriiDobronos/pull/3#discussion_r1582894849>
> :
>
> > \ No newline at end of file
> +const config = require('config');
> +const {logLevel} = require("./config/default");
>
> звертання до ключа logLevel із config чимось відрізняється від ключа
> colorsEnabled? :) для чого зроблена різниця?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AndriiDobronos/nodejs24_hw_AndriiDobronos/pull/3#pullrequestreview-2028170889>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3URRGEHDXUWNRAVVKQIWZDY7YVBVAVCNFSM6AAAAABG26AG5KVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAMRYGE3TAOBYHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> .com>
>

2024-04-29 11:33 UTC, AndriiDobronos commented
Дякую

Пн, 29 апр. 2024 г. в 14:31, Yevhen Hraivoronskyi ***@***.***
>:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In utils/logger.js
> <https://github.com/AndriiDobronos/nodejs24_hw_AndriiDobronos/pull/3#discussion_r1582898517>
> :
>
> >
> -function info(msg) {
> -    console.log(property,':',msg);
> +function getLogger(moduleName,colorsEnabled,logLevel) {
>
> взагалі, сама ідея передавати конфіг ззовні хороша. Просто тоді краще
> передавати логгер конфіг не двома окремими параметрами, а одним об'єктом. Я
> тобі закомітив трохи допомоги, показав як це зробити краще, подивись
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AndriiDobronos/nodejs24_hw_AndriiDobronos/pull/3#pullrequestreview-2028177059>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3URRGEDDW2PYYZQ7YOVID3Y7YVPTAVCNFSM6AAAAABG26AG5KVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAMRYGE3TOMBVHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> .com>
>

2024-04-29 11:34 UTC, evhenious commented on utils/logger.js
> +function getLogger(moduleName, loggerConfig) {
Дуже багато додаткової логіки накрутив для виключення кольорів. Не лінуйся читати документацію на інструменти, які використовуєш - пакет `colors` дає один дуже зручний метод для вимкнення кольорів - я тобі закинув коміт який це поправив, подивись

2024-04-29 11:39 UTC, evhenious commented on utils/logger.js
> +    switch(logLevel) {
І тут також забагато непотрібних слів написано )) свіч, який перевизначає повністю всі методи логера... а уяви, потрібно буде помінять поведінку метода `warn` - доведеться виправляти аж в 4 місцях, при тому що по сути методи однакові в усіх варіантах... 
Куди простіше і коротше зробити це прямо в самих методах - я тобі поправив як краще, подивись

2024-04-29 11:41 UTC, AndriiDobronos commented
Thank you for your answer.

Пн, 29 апр. 2024 г. в 14:40, Yevhen Hraivoronskyi ***@***.***
>:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In utils/logger.js
> <https://github.com/AndriiDobronos/nodejs24_hw_AndriiDobronos/pull/3#discussion_r1582920774>
> :
>
> >
> -function logger(arg)  {
> -    property = arg
> -    return {info, warn, error}
> +    switch(logLevel) {
>
> І тут також забагато непотрібних слів написано )) свіч, який перевизначає
> повністю всі методи логера... а уяви, потрібно буде помінять поведінку
> метода warn - доведеться виправляти аж в 4 місцях, при тому що по сути
> методи однакові в усіх варіантах...
> Куди простіше і коротше зробити це прямо в самих методах - я тобі поправив
> як краще, подивись
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AndriiDobronos/nodejs24_hw_AndriiDobronos/pull/3#pullrequestreview-2028217726>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3URRGB2C6BQNW74MLI3QLLY7YWRJAVCNFSM6AAAAABG26AG5KVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAMRYGIYTONZSGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> .com>
>

2024-04-29 11:43 UTC, merged