added homework_4
AndriiDobronos/nodejs24_hw_AndriiDobronos pull request #8
Opened 2024-05-03 11:37 UTC by AndriiDobronos

2024-05-03 17:54 UTC, evhenious commented on file_sync.js
> +const logger = require('./utils/logger')('file_sync',config);
👍

2024-05-03 17:56 UTC, evhenious commented on logs/error.log.txt
Логи не треба комітити в гіт. Вони взагалі мають бути автоматично в списку gitignore, чому вони тут? 
Бачиш, у тебе вийшли файли з подвійним розширенням? .log.txt
Прибери це будь ласка, хай файли будуть просто з розширенням .log (плюсом, вони після цього мають попасти в ігнорліст і не комітитись більше)

2024-05-03 18:13 UTC, evhenious requested changes
Я бачу ти любиш експериментувати, робити декілька варіантів на щось, тримати закоментованими старі версії коду і подібне. Тяга до експериментів це круто. АЛЕ. Такі пулріквесті **_дуже_** складно перевіряти. 
Давай домовимось - коли здаєш мені домашку - вибери ОДИН варіант імплементації, який тобі подобається найбільше, доведи до робочого стану і здавай.

Також не треба тримати старий код в коментарях - це все теж ускладнює читання. В нас гіт - система контролю версій. Це значить, що весь код з будь-якого моменту історії (навіть той який ти в якийсь момент видалив) завжди доступний - просто відкрий потрібний файл із старого коміта і подивись. 

Тож конкретно зараз, для тебе головне: почистити всякі другі, треті версії логерів створених "про всяк випадок", подвійні місця створення стрімов, тонни закоментованого старого коду і подібне. Бо зараз я не сильно розумію ЩО САМЕ я маю перевірити. Добре?

Нагадую, станом на зараз у тебе має бути: один логгер, який регулюється конфігом (кольори і методи яки пишуть в термінал). В цьому логгері ти видкриваєш два файл стріма на запис, куди пишеш всі лог месаджі. На івенті `beforeExit` у об'єкта `process` ти закриваєш файл стріми. 

На тому й все :)

2024-05-04 06:33 UTC, AndriiDobronos commented
Дуже слушні зауваження про чистоту коду він дуже далекий від «Solid»
патерна проектування. Я просто ще не звик що є такі речі як коміти. Буду
намагатися робити код чистішим. І ще для мене було відкриттям що текстові
файли можуть бути з  розширенням    .log
а не . txt треба про це почитати.
Пт, 3 мая 2024 г. в 21:14, Yevhen Hraivoronskyi ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> Я бачу ти любиш експериментувати, робити декілька варіантів на щось,
> тримати закоментованими старі версії коду і подібне. Тяга до експериментів
> це круто. АЛЕ. Такі пулріквесті *дуже* складно перевіряти.
> Давай домовимось - коли здаєш мені домашку - вибери ОДИН варіант
> імплементації, який тобі подобається найбільше, доведи до робочого стану і
> здавай.
>
> Також не треба тримати старий код в коментарях - це все теж ускладнює
> читання. В нас гіт - система контролю версій. Це значить, що весь код з
> будь-якого моменту історії (навіть той який ти в якийсь момент видалив)
> завжди доступний - просто відкрий потрібний файл із старого коміта і
> подивись.
>
> Тож конкретно зараз, для тебе головне: почистити всякі другі, треті версії
> логерів створених "про всяк випадок", подвійні місця створення стрімов,
> тонни закоментованого старого коду і подібне. Бо зараз я не сильно розумію
> ЩО САМЕ я маю перевірити. Добре?
>
> Нагадую, станом на зараз у тебе має бути: один логгер, який регулюється
> конфігом (кольори і методи яки пишуть в термінал). В цьому логгері ти
> видкриваєш два файл стріма на запис, куди пишеш всі лог месаджі. На івенті
> beforeExit у об'єкта process ти закриваєш файл стріми.
>
> На тому й все :)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AndriiDobronos/nodejs24_hw_AndriiDobronos/pull/8#pullrequestreview-2038762956>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3URRGAF4KB2HLFK6LUPRKDZAPHWRAVCNFSM6AAAAABHFLSPPOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAMZYG43DEOJVGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> .com>
>

2024-05-04 07:53 UTC, evhenious commented
Це поки що не зовсім про SOLID, а більше про інші принципи - Keep It Simple
+ You Aren't Gonna Need It. Можеш почитати отут статейку, непогано описано
https://senior.ua/articles/kiss-dry-solid-yagni--navscho-dotrimuvatis-principv-programuvannya

On Sat, May 4, 2024, 09:34 Andrii ***@***.***> wrote:

> Дуже слушні зауваження про чистоту коду він дуже далекий від «Solid»
> патерна проектування. Я просто ще не звик що є такі речі як коміти. Буду
> намагатися робити код чистішим. І ще для мене було відкриттям що текстові
> файли можуть бути з розширенням .log
> а не . txt треба про це почитати.
> Пт, 3 мая 2024 г. в 21:14, Yevhen Hraivoronskyi ***@***.***>:
>
> > ***@***.**** requested changes on this pull request.
> >
> > Я бачу ти любиш експериментувати, робити декілька варіантів на щось,
> > тримати закоментованими старі версії коду і подібне. Тяга до
> експериментів
> > це круто. АЛЕ. Такі пулріквесті *дуже* складно перевіряти.
> > Давай домовимось - коли здаєш мені домашку - вибери ОДИН варіант
> > імплементації, який тобі подобається найбільше, доведи до робочого стану
> і
> > здавай.
> >
> > Також не треба тримати старий код в коментарях - це все теж ускладнює
> > читання. В нас гіт - система контролю версій. Це значить, що весь код з
> > будь-якого моменту історії (навіть той який ти в якийсь момент видалив)
> > завжди доступний - просто відкрий потрібний файл із старого коміта і
> > подивись.
> >
> > Тож конкретно зараз, для тебе головне: почистити всякі другі, треті
> версії
> > логерів створених "про всяк випадок", подвійні місця створення стрімов,
> > тонни закоментованого старого коду і подібне. Бо зараз я не сильно
> розумію
> > ЩО САМЕ я маю перевірити. Добре?
> >
> > Нагадую, станом на зараз у тебе має бути: один логгер, який регулюється
> > конфігом (кольори і методи яки пишуть в термінал). В цьому логгері ти
> > видкриваєш два файл стріма на запис, куди пишеш всі лог месаджі. На
> івенті
> > beforeExit у об'єкта process ти закриваєш файл стріми.
> >
> > На тому й все :)
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/AndriiDobronos/nodejs24_hw_AndriiDobronos/pull/8#pullrequestreview-2038762956>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/A3URRGAF4KB2HLFK6LUPRKDZAPHWRAVCNFSM6AAAAABHFLSPPOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAMZYG43DEOJVGY>
>
> > .
> > You are receiving this because you authored the thread.Message ID:
> > ***@***.***
> > .com>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AndriiDobronos/nodejs24_hw_AndriiDobronos/pull/8#issuecomment-2094048692>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABIBTG2HLRQBEA5RVD2B64TZAR6N5AVCNFSM6AAAAABHFLSPPOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAOJUGA2DQNRZGI>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-05-04 17:19 UTC, evhenious approved these changes
Так набагато краще, велике дякую що прийняв до уваги мої коментарі!

2024-05-04 17:19 UTC, merged